# Generated by Django 5.1 on 2024-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_posts_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="falback.png", upload_to=""),
        ),
    ]
